name: Ejecutar script en Python

on:
  push:
  workflow_dispatch:
jobs:
  ejecutar-python:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Ejecutar script
        run: python arhivo-que-no-existe.py
